export const collections = {
  users: "users",
  businesses: "businesses",
  transactions: "transactions",
  debts: "debts",
  loans: "loans",
  inventory: "inventory",
  summaries: "summaries",
  notifications: "notifications",
  whatsappSessions: "whatsapp_sessions",
  referrals: "referrals",
  withdrawals: "withdrawals",
  paymentClaims: "payment_claims",
  errors: "errors",
} as const;
