/**
 * ZURIA AI Pipeline
 *
 * The unified entry point for all intelligence processing in ZURIA.
 * Replaces the simple getActiveProvider() call with a fully orchestrated
 * pipeline that runs:
 *
 *   1. Safety moderation (deterministic + optional Groq guard)
 *   2. Memory loading (business profile + contextual memory)
 *   3. Confidence routing (deterministic / fast AI / advanced AI)
 *   4. Shadow learning (fire-and-forget, never blocks)
 *   5. Parser learning (training data collection)
 *   6. Event emission (for observability)
 *
 * The caller (WhatsApp/Telegram handler) continues to receive a simple
 * string response — the pipeline is completely transparent.
 *
 * All failures are fail-open: if any stage fails, the rule-based response
 * is returned. ZURIA must never go silent because of an AI failure.
 *
 * Server-only.
 */

import type { ParsedTransaction } from "@/types/domain";
import type { AIGenerateRequest } from "@/lib/intelligence/ai-provider";

// ─── Pipeline input ───────────────────────────────────────────────────────────

export interface PipelineInput {
  userId: string;
  businessId: string;
  rawText: string;
  normalizedText: string;
  parsedTransaction: ParsedTransaction;
  aiRequest: AIGenerateRequest;
  intentLabel: string;
  isCriticalTransaction?: boolean;
  platform?: "whatsapp" | "telegram";
  /** The rule-based response already generated by response-engine.ts */
  ruleBasedResponse: string;
}

// ─── Pipeline output ──────────────────────────────────────────────────────────

export interface PipelineOutput {
  /** Final response to send to the user */
  response: string;
  /** Whether AI was used for this response */
  usedAI: boolean;
  /** Which AI model was used */
  aiModel?: string;
  /** Routing path taken */
  routingPath: "deterministic" | "ai_enhanced" | "ai_reasoning" | "fallback" | "blocked";
  /** Whether moderation blocked this input */
  blocked: boolean;
}

// ─── Main pipeline ────────────────────────────────────────────────────────────

/**
 * Run the complete ZURIA AI pipeline for a single user message.
 *
 * This is the RECOMMENDED entry point for all message processing.
 * Falls back gracefully at every stage.
 */
export async function runAIPipeline(input: PipelineInput): Promise<PipelineOutput> {
  const {
    userId, businessId, rawText, normalizedText,
    parsedTransaction, aiRequest, isCriticalTransaction = false,
    platform = "whatsapp", ruleBasedResponse,
  } = input;

  // ── Stage 1: Safety moderation ──────────────────────────────────────────
  try {
    const { fullModeration } = await import("./safety/moderator");
    const modResult = await fullModeration(rawText);
    if (!modResult.safe) {
      // Emit security event (fire-and-forget)
      void (async () => {
        try {
          const { emitSecurityEvent } = await import("@/lib/events/emitter");
          emitSecurityEvent(userId, "security.moderation_blocked", modResult.reason ?? "unsafe input");
        } catch { /* silent */ }
      })();
      return {
        response:     "I couldn't process that message. Please try again with a clear business transaction.",
        usedAI:       false,
        routingPath:  "blocked",
        blocked:      true,
      };
    }
  } catch {
    // Moderation failure → fail-open (continue processing)
  }

  // ── Stage 2: Shadow learning (fire-and-forget, before AI) ───────────────
  try {
    const { runShadowLearning } = await import("@/lib/intelligence/shadow-learner");
    runShadowLearning(userId, rawText, normalizedText, parsedTransaction);
  } catch { /* never block on shadow learning */ }

  // ── Stage 3: Check feature flags ────────────────────────────────────────
  let aiEnabled = true;
  try {
    const { getFlagSync, FLAGS } = await import("@/lib/feature-flags");
    aiEnabled = getFlagSync(FLAGS.AI_ENABLED);
  } catch { /* default enabled */ }

  // ── Stage 4: Build memory-enriched context ───────────────────────────────
  let enrichedAIRequest = aiRequest;
  try {
    const { loadMemory } = await import("@/lib/memory");
    const memory = await loadMemory(userId, businessId);
    if (memory.contextSummary) {
      // Inject memory into AI request's businessContext
      enrichedAIRequest = {
        ...aiRequest,
        businessContext: `${aiRequest.businessContext}. ${memory.contextSummary}`,
      };
    }
  } catch { /* memory failure → use plain context */ }

  // ── Stage 5: AI orchestration ────────────────────────────────────────────
  if (!aiEnabled) {
    // AI disabled via feature flag → pure deterministic
    void collectLearningExample(input, null);
    return {
      response:    ruleBasedResponse,
      usedAI:      false,
      routingPath: "deterministic",
      blocked:     false,
    };
  }

  try {
    const { groqGenerate, isGroqAvailable } = await import("./groq");
    const { ZURIA_SYSTEM_PROMPT } = await import("@/lib/intelligence/ai-provider");
    const { CONF_HIGH, CONF_MEDIUM } = await import("./orchestrator");

    const conf = parsedTransaction.confidence;

    // HIGH confidence → deterministic save, no AI needed (except shadow learning above)
    if (conf >= CONF_HIGH) {
      void collectLearningExample(input, null);
      void emitTransactionEvent(userId, parsedTransaction, "deterministic", platform);
      return {
        response:    ruleBasedResponse,
        usedAI:      false,
        routingPath: "deterministic",
        blocked:     false,
      };
    }

    // MEDIUM or LOW confidence → route to AI
    if (!isGroqAvailable()) {
      // Groq not configured → use rule-based fallback
      void collectLearningExample(input, null);
      return {
        response:    ruleBasedResponse,
        usedAI:      false,
        routingPath: "fallback",
        blocked:     false,
      };
    }

    const model = conf >= CONF_MEDIUM ? "fast" : "advanced";

    const userPrompt = buildAIPrompt(enrichedAIRequest);

    const aiResult = await groqGenerate(userPrompt, {
      model,
      maxTokens:    220,
      temperature:  0.55,
      systemPrompt: ZURIA_SYSTEM_PROMPT,
    });

    if (!aiResult?.text) {
      // AI produced nothing → rule-based fallback
      void collectLearningExample(input, null);
      return {
        response:    ruleBasedResponse,
        usedAI:      false,
        routingPath: "fallback",
        blocked:     false,
      };
    }

    // Record AI usage
    void recordUsage(userId, model, aiResult);

    // Collect training example (fire-and-forget)
    void collectLearningExample(input, aiResult.text);

    // Emit event (fire-and-forget)
    void emitTransactionEvent(userId, parsedTransaction, conf >= CONF_MEDIUM ? "ai_enhanced" : "ai_reasoning", platform);

    return {
      response:    aiResult.text,
      usedAI:      true,
      aiModel:     aiResult.model,
      routingPath: conf >= CONF_MEDIUM ? "ai_enhanced" : "ai_reasoning",
      blocked:     false,
    };

  } catch {
    // Any AI failure → rule-based fallback
    void collectLearningExample(input, null);
    return {
      response:    ruleBasedResponse,
      usedAI:      false,
      routingPath: "fallback",
      blocked:     false,
    };
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Build the AI prompt from the enriched request.
 */
function buildAIPrompt(req: AIGenerateRequest): string {
  return [
    `Business context: ${req.businessContext}`,
    req.financialContext  ? `Financial data: ${req.financialContext}`          : null,
    req.intentContext     ? `Classified intent: ${req.intentContext}`           : null,
    req.emotionalTone && req.emotionalTone !== "neutral"
                          ? `Emotional tone: ${req.emotionalTone}`             : null,
    req.conversationHistory ? `Recent conversation:\n${req.conversationHistory}` : null,
    `User message: "${req.currentMessage}"`,
    `Generate a brief ZURIA response. 2–4 lines max. No JSON. No internal labels. Just the reply.`,
  ].filter(Boolean).join("\n");
}

/**
 * Fire-and-forget: collect a training example if appropriate.
 */
async function collectLearningExample(
  input: PipelineInput,
  aiResponse: string | null,
): Promise<void> {
  try {
    const { collectTrainingExample, shouldCollectExample, detectLanguage }
      = await import("@/lib/parser-learning/collector");

    if (!shouldCollectExample(input.parsedTransaction.confidence, aiResponse)) return;

    await collectTrainingExample({
      rawInput:        input.rawText.slice(0, 500),
      normalizedInput: input.normalizedText.slice(0, 500),
      parserResult: {
        type:         input.parsedTransaction.type,
        amount:       input.parsedTransaction.amount,
        confidence:   input.parsedTransaction.confidence,
        productName:  input.parsedTransaction.productName,
        customerName: input.parsedTransaction.customerName,
      },
      aiResult: aiResponse
        ? { type: null, amount: null, confidence: 0.8, response: aiResponse.slice(0, 300) }
        : null,
      acceptedResult: {
        type:   input.parsedTransaction.type,
        amount: input.parsedTransaction.amount,
      },
      language:         detectLanguage(input.rawText),
      businessCategory: "other",
      userId:           input.userId,
      diverged:         false,
    });
  } catch { /* never block */ }
}

/**
 * Fire-and-forget: record AI usage for cost governance.
 */
async function recordUsage(
  userId: string,
  model: "fast" | "advanced",
  aiResult: { model: string; inputTokens: number; outputTokens: number; latencyMs: number },
): Promise<void> {
  try {
    const { recordAIUsage, estimateCost } = await import("./cost-governance");
    await recordAIUsage({
      userId,
      model:               aiResult.model,
      inputTokens:         aiResult.inputTokens,
      outputTokens:        aiResult.outputTokens,
      estimatedCostUSD:    estimateCost(model, aiResult.inputTokens, aiResult.outputTokens),
      latencyMs:           aiResult.latencyMs,
      routingPath:         model === "fast" ? "ai_enhanced" : "ai_reasoning",
    });
  } catch { /* never block */ }
}

/**
 * Fire-and-forget: emit transaction event for monitoring.
 */
async function emitTransactionEvent(
  userId: string,
  parsed: ParsedTransaction,
  routingPath: string,
  platform: string,
): Promise<void> {
  try {
    const { emitTransactionCreated } = await import("@/lib/events/emitter");
    emitTransactionCreated(userId, {
      transactionId: crypto.randomUUID(),
      type:          parsed.type,
      amount:        parsed.amount,
      confidence:    parsed.confidence,
      usedAI:        routingPath !== "deterministic",
    });
    void platform; // used implicitly
  } catch { /* never block */ }
}
